### PR TITLE
#118 - New hover-freeze and toggle-freeze

### PR DESCRIPTION
**Pull request by felipealbuquerq**
[For this Issue](https://github.com/wittlock/ngx-image-zoom/issues/118)

### CODE REVIEW

**Comment by wittlock** [comment]
Hi,
Thanks for this pull request. This looks like a reasonable change. I'd just like to try it out a little bit before merging and releasing it, but I should be able to find some time for that in the next several days.
One change I'd like to request though is to remove the various links to examples and demos. I have my own page with demos that I'll update to show this new feature. I'd rather keep it all gathered in one place on my github pages. They're hiding in the gh-pages branch if you want to make a PR for updating those too.

**Comment by felipealbuquerq** [comment]
Sounds good, @wittlock!

I'll change it soon, I didn't know about the hidden pages... Thanks for this info!

**Comment by felipealbuquerq** [comment]
@wittlock I did a new example and the [PR is open](https://github.com/wittlock/ngx-image-zoom/pull/122)

**Comment by felipealbuquerq** [comment]
@wittlock About the others adjustments: I'll change it soon.

**Comment by felipealbuquerq** [comment]
@wittlock ✔️Done!

**Comment by wittlock** [comment]
I haven't forgotten about this. It looks good now. I just have been quite busy lately so I haven't had time to do a quick test and package a release. I promise I'm trying to find some time for it as soon as I can.

I'm also terribly sorry that I was unclear and you went through the trouble of updating the example. I just meant you could remove the links to the other one and I would have updated it. Recreating it without access to the source sounds like a pain. I appreciate the effort though!

Hang tight, hopefully a release can happen during this week sometime!

**Comment by felipealbuquerq** [comment]
No problem!

**Review by wittlock — APPROVED** [review]

**Pull request merged**
