### PR TITLE
Issue#6 fix - accurate zoom even for reduced size thumb image

### PR DESCRIPTION
**Pull request by veeru1087**
Hello, 
I fixed an issue with reduced thumb images are showing inaccurate zoom position. Please take a look at changes and merge it after making sure that it does not break something else you have planned for.

### CODE REVIEW

**Comment by wittlock** [comment]
Hi there,
Thank you for the pull request! I just got back from an extended trip (traveling for a month). This does look like a neat and minimal change though, but I want to run it through my various tests before merging it. Hoping to find some time and energy in the next few weeks to dive back into this project again and I'll start with looking at this.

**Comment by veeru1087** [comment]
@wittlock  Can you merge this PR? I see many people suffering with this issue.

**Comment by w1lltj** [comment]
Hi @wittlock  ,
Thank you very much for great Angular component. Appreciate the effort!
Just a request for help though. I also face similar issue as the rest regarding to "thumbImage" size.
I have tried solution provided by @veeru1087  . It works perfectly (Thanks @veeru1087 !!).
Could you help to approve the PR created by @veeru1087 please 🙏

Thanks!!

**Comment by wittlock** [comment]
Hey guys, sorry for my absence but life got a bit crazy last couple of months.
I think I have time this weekend or next week when I have some time off to go through the pull requests and issues here and I'll merge anything that doesn't look problematic and try to fix another couple of things. So please bear with me a few more days! :)

**Comment by gr33ngr33n** [comment]
Hi @wittlock,
Can you merge this PR please? It seems like many people suffering with this issue.

**Comment by wittlock** [comment]
This should now be on npm as version 0.4.0, hope it works to your liking and sorry about the extended delays.

**Comment by wittlock** [comment]
This fix actually broke a couple of my test cases. I must have messed up trying to test it out because I didn't notice it before. I'm going to release a 0.4.1 with some further tweaks (rollback of part of the changes in this PR) that might break your use case. But to make sure there's a version working for those who depend on the old behavior. I'm then going to try and build a test case replicating your issues and see if it needs further fixes, but feel free to report back if 0.4.1 breaks it or not. And if it does break it a minimal test case would be greatly appreciated.

**Comment by gr33ngr33n** [comment]
@wittlock Thanks for your time! Appreciate it!

**Pull request merged**
